// <auto-generated />
using System;
using DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbContext.Migrations.SqlServerDbContext
{
    [DbContext(typeof(csMainDbContext.SqlServerDbContext))]
    [Migration("20241005094212_miInitial")]
    partial class miInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbModels.csSightDbM", b =>
                {
                    b.Property<Guid>("SightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<Guid?>("CountryDbMCountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.Property<string>("strCategory")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SightId");

                    b.HasIndex("CountryDbMCountryId");

                    b.ToTable("Sights");
                });

            modelBuilder.Entity("Models.DTO.csCountryDbM", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("CountryId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("csCityDbM", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CountryDbMCountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("CityId");

                    b.HasIndex("CountryDbMCountryId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("csCityDbMcsSightDbM", b =>
                {
                    b.Property<Guid>("CitiesDbMCityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SightsDbMSightId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CitiesDbMCityId", "SightsDbMSightId");

                    b.HasIndex("SightsDbMSightId");

                    b.ToTable("csCityDbMcsSightDbM");
                });

            modelBuilder.Entity("csCommentsDbM", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserDbMUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentId");

                    b.HasIndex("UserDbMUserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("csCommentsDbMcsSightDbM", b =>
                {
                    b.Property<Guid>("CommentDbMCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SightsDbMSightId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentDbMCommentId", "SightsDbMSightId");

                    b.HasIndex("SightsDbMSightId");

                    b.ToTable("csCommentsDbMcsSightDbM");
                });

            modelBuilder.Entity("csUserDbM", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DbModels.csSightDbM", b =>
                {
                    b.HasOne("Models.DTO.csCountryDbM", "CountryDbM")
                        .WithMany("SightsDbM")
                        .HasForeignKey("CountryDbMCountryId");

                    b.Navigation("CountryDbM");
                });

            modelBuilder.Entity("csCityDbM", b =>
                {
                    b.HasOne("Models.DTO.csCountryDbM", "CountryDbM")
                        .WithMany("CitiesDbM")
                        .HasForeignKey("CountryDbMCountryId");

                    b.Navigation("CountryDbM");
                });

            modelBuilder.Entity("csCityDbMcsSightDbM", b =>
                {
                    b.HasOne("csCityDbM", null)
                        .WithMany()
                        .HasForeignKey("CitiesDbMCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModels.csSightDbM", null)
                        .WithMany()
                        .HasForeignKey("SightsDbMSightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("csCommentsDbM", b =>
                {
                    b.HasOne("csUserDbM", "UserDbM")
                        .WithMany("CommentDbM")
                        .HasForeignKey("UserDbMUserId");

                    b.Navigation("UserDbM");
                });

            modelBuilder.Entity("csCommentsDbMcsSightDbM", b =>
                {
                    b.HasOne("csCommentsDbM", null)
                        .WithMany()
                        .HasForeignKey("CommentDbMCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModels.csSightDbM", null)
                        .WithMany()
                        .HasForeignKey("SightsDbMSightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.DTO.csCountryDbM", b =>
                {
                    b.Navigation("CitiesDbM");

                    b.Navigation("SightsDbM");
                });

            modelBuilder.Entity("csUserDbM", b =>
                {
                    b.Navigation("CommentDbM");
                });
#pragma warning restore 612, 618
        }
    }
}
